version: '3.0'
services:
  node:
    build: .
    container_name: server
    ports:
      - ${PORT}:${PORT}
    networks:
      - custom_network
    depends_on:
      - postgres
    volumes:
      - node:/usr/app/logs
  postgres:
    build: ./database/
    container_name: database
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - custom_network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  custom_network:
    driver: bridge
volumes:
  node:
  postgres:
