version: '3'
services:
  node:
    image: alekseylevko/rsschool:server
    build: .
    container_name: server
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    networks:
      - custom_network
    depends_on:
      - postgres
    volumes:
      - node:/usr/app/logs
      - type: bind
        source: ./src
        target: /usr/app/src
  postgres:
    image: alekseylevko/rsschool:database
    build: ./database/
    container_name: database
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - custom_network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  custom_network:
    driver: bridge
volumes:
  node:
  postgres:
